#!/usr/bin/env python3
"""Generate constrained-random RV32I assembly programs for the core harness.

The generator intentionally emits readable .S files instead of raw hex. That
keeps failing seeds easy to inspect with objdump and preserves the existing
assembly -> hex -> rv32i_ref.py -> expected-file flow.
"""

from __future__ import annotations

import argparse
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Callable


ALL_CATEGORIES = ("alu", "mem", "branch", "u", "jump")
CATEGORY_WEIGHTS = {
    "alu": 58,
    "mem": 20,
    "branch": 14,
    "u": 5,
    "jump": 3,
}

ADDR_REG = 31
TMP_REG = 30
BR_RS1 = 28
BR_RS2 = 29
BR_RESULT = 27
JUMP_RESULT = 26

NONZERO_WRITE_REGS = tuple(reg for reg in range(1, 31))
SOURCE_REGS = tuple(reg for reg in range(0, 31))
GENERAL_INIT_REGS = tuple(reg for reg in range(1, 31))

R_TYPE_OPS = ("add", "sub", "and", "or", "xor", "sll", "srl", "sra", "slt", "sltu")
I_TYPE_OPS = ("addi", "slti", "sltiu", "xori", "ori", "andi")
SHIFT_IMM_OPS = ("slli", "srli", "srai")
BRANCH_OPS = ("beq", "bne", "blt", "bge", "bltu", "bgeu")
U_TYPE_OPS = ("lui", "auipc")

INTERESTING_IMM12 = (
    -2048,
    -1024,
    -129,
    -128,
    -17,
    -16,
    -2,
    -1,
    0,
    1,
    2,
    3,
    4,
    7,
    8,
    15,
    16,
    31,
    32,
    63,
    64,
    127,
    128,
    255,
    256,
    511,
    1023,
    2047,
)


class GeneratorError(RuntimeError):
    pass


@dataclass(frozen=True)
class GeneratorConfig:
    seed: int
    name: str
    instr_count: int
    categories: tuple[str, ...]
    output: Path | None
    signature_words: int
    scratch_base: int
    scratch_words: int
    random_imm_rate: float
    data_base: int = 0

    def validate(self) -> None:
        unknown = sorted(set(self.categories) - set(ALL_CATEGORIES))
        if unknown:
            raise GeneratorError(f"unknown categories: {', '.join(unknown)}")
        if not self.categories:
            raise GeneratorError("at least one category is required")
        if self.instr_count < 0:
            raise GeneratorError("--instr-count must be non-negative")
        if not (1 <= self.signature_words <= 32):
            raise GeneratorError("--signature-words must be in range 1..32")
        if self.scratch_base < 0 or self.scratch_base % 4:
            raise GeneratorError("--scratch-base must be a non-negative aligned address")
        if not (1 <= self.scratch_words <= 128):
            raise GeneratorError("--scratch-words must be in range 1..128")
        highest = self.scratch_base + 4 * (self.scratch_words - 1)
        if highest > 1020:
            raise GeneratorError("scratch memory must stay inside dmem[0:255]")
        if not (0.0 <= self.random_imm_rate <= 1.0):
            raise GeneratorError("--random-imm-rate must be in range 0.0..1.0")
        if not (0 <= self.data_base <= 0xFFFFFFFF) or self.data_base % 0x1000:
            raise GeneratorError("--data-base must be a 4 KB aligned 32-bit address")
        # With a nonzero data base the signature is stored through ADDR_REG, at
        # offsets 4*reg - scratch_base, which must fit a signed imm12.
        if self.data_base and self.scratch_base > 2048:
            raise GeneratorError("--scratch-base must be <= 2048 when --data-base is set")


class ProgramBuilder:
    def __init__(self, config: GeneratorConfig) -> None:
        self.config = config
        self.lines: list[str] = []
        self.label_index = 0
        self.trace_index = 0

    def comment(self, text: str = "") -> None:
        self.lines.append(f"  # {text}" if text else "")

    def emit(self, text: str = "") -> None:
        self.lines.append(f"  {text}" if text else "")

    def label(self, prefix: str) -> str:
        label = f"{self.config.name}_{prefix}_{self.label_index}"
        self.label_index += 1
        return label

    def place_label(self, label: str) -> None:
        self.lines.append(f"{label}:")

    def next_trace_offset(self) -> int:
        offset = 4 * (self.trace_index % self.config.scratch_words)
        self.trace_index += 1
        return offset

    def render(self) -> str:
        header = [
            f"# Generated by tools/gen_random_program.py",
            f"# name: {self.config.name}",
            f"# seed: {self.config.seed}",
            f"# instr_count: {self.config.instr_count}",
            f"# categories: {','.join(self.config.categories)}",
            f"# scratch_base: 0x{self.config.scratch_base:08x}",
            f"# scratch_words: {self.config.scratch_words}",
        ]
        if self.config.data_base:
            header.append(f"# data_base: 0x{self.config.data_base:08x}")
        header += [
            "# constraints: legal supported subset only",
            "# constraints: aligned LW/SW only",
            "# constraints: forward-only branch/JAL blocks, no JALR, no loops",
            "",
            f"{self.config.name}:",
        ]
        return "\n".join(header + self.lines + [""])


class RandomProgramGenerator:
    def __init__(self, config: GeneratorConfig) -> None:
        config.validate()
        self.config = config
        self.rng = random.Random(config.seed)
        self.builder = ProgramBuilder(config)
        self.emitters: dict[str, Callable[[], None]] = {
            "alu": self.emit_alu_op,
            "mem": self.emit_mem_op,
            "branch": self.emit_branch_block,
            "u": self.emit_u_type_op,
            "jump": self.emit_jump_block,
        }

    def generate(self) -> str:
        self.emit_prelude()

        self.builder.comment("random body")
        for index in range(self.config.instr_count):
            category = self.choose_category()
            self.builder.comment(f"op {index:03d}: {category}")
            self.emitters[category]()

        self.emit_signature_dump()
        return self.builder.render()

    def choose_category(self) -> str:
        weights = [CATEGORY_WEIGHTS[category] for category in self.config.categories]
        return self.rng.choices(self.config.categories, weights=weights, k=1)[0]

    def emit_prelude(self) -> None:
        self.builder.comment("deterministic register initialization")
        for reg in GENERAL_INIT_REGS:
            self.builder.emit(f"addi x{reg}, x0, {self.imm12()}")

        self.builder.comment("aligned scratch-memory base")
        addr = self.config.data_base + self.config.scratch_base
        if -2048 <= addr <= 2047:
            self.builder.emit(f"addi x{ADDR_REG}, x0, {addr}")
        else:
            hi = ((addr + 0x800) >> 12) & 0xFFFFF
            lo = addr - (((addr + 0x800) >> 12) << 12)
            self.builder.emit(f"lui  x{ADDR_REG}, 0x{hi:x}")
            self.builder.emit(f"addi x{ADDR_REG}, x{ADDR_REG}, {lo}")

        self.builder.comment("deterministic scratch-memory initialization")
        for word_index in range(self.config.scratch_words):
            self.builder.emit(f"addi x{TMP_REG}, x0, {self.imm12()}")
            self.builder.emit(f"sw   x{TMP_REG}, {4 * word_index}(x{ADDR_REG})")
        self.builder.emit()

    def emit_signature_dump(self) -> None:
        self.builder.emit()
        self.builder.comment("final architectural signature")
        for reg in range(self.config.signature_words):
            if self.config.data_base:
                # ADDR_REG = data_base + scratch_base and is never a random rd.
                self.builder.emit(f"sw   x{reg}, {4 * reg - self.config.scratch_base}(x{ADDR_REG})")
            else:
                self.builder.emit(f"sw   x{reg}, {4 * reg}(x0)")

    def emit_alu_op(self) -> None:
        form = self.rng.choice(("r", "i", "shift_i"))
        rd = self.write_reg()

        if form == "r":
            op = self.rng.choice(R_TYPE_OPS)
            rs1 = self.source_reg()
            rs2 = self.source_reg()
            self.builder.emit(f"{op:<4} x{rd}, x{rs1}, x{rs2}")
        elif form == "i":
            op = self.rng.choice(I_TYPE_OPS)
            rs1 = self.source_reg()
            self.builder.emit(f"{op:<4} x{rd}, x{rs1}, {self.imm12()}")
        else:
            op = self.rng.choice(SHIFT_IMM_OPS)
            rs1 = self.source_reg()
            self.builder.emit(f"{op:<4} x{rd}, x{rs1}, {self.rng.randrange(32)}")

    def emit_mem_op(self) -> None:
        offset = 4 * self.rng.randrange(self.config.scratch_words)
        if self.rng.random() < 0.55:
            rs2 = self.source_reg()
            self.builder.emit(f"sw   x{rs2}, {offset}(x{ADDR_REG})")
        else:
            rd = self.write_reg()
            self.builder.emit(f"lw   x{rd}, {offset}(x{ADDR_REG})")

    def emit_branch_block(self) -> None:
        op = self.rng.choice(BRANCH_OPS)
        taken = self.rng.choice((False, True))
        left, right = self.branch_operands(op, taken)
        taken_label = self.builder.label("br_taken")
        done_label = self.builder.label("br_done")
        fall_value = self.distinct_imm12()
        taken_value = self.distinct_imm12(exclude=fall_value)

        self.builder.emit(f"addi x{BR_RS1}, x0, {left}")
        self.builder.emit(f"addi x{BR_RS2}, x0, {right}")
        self.builder.emit(f"{op:<4} x{BR_RS1}, x{BR_RS2}, {taken_label}")
        self.builder.emit(f"addi x{BR_RESULT}, x0, {fall_value}")
        self.builder.emit(f"jal  x0, {done_label}")
        self.builder.place_label(taken_label)
        self.builder.emit(f"addi x{BR_RESULT}, x0, {taken_value}")
        self.builder.place_label(done_label)
        self.builder.emit(f"sw   x{BR_RESULT}, {self.builder.next_trace_offset()}(x{ADDR_REG})")

    def emit_u_type_op(self) -> None:
        op = self.rng.choice(U_TYPE_OPS)
        rd = self.write_reg()
        imm20 = self.rng.choice((0x0, 0x1, 0x7F, 0x80, 0x12345, 0x7FFFF, 0x80000, 0xFFFFF))
        self.builder.emit(f"{op:<5} x{rd}, 0x{imm20:x}")

    def emit_jump_block(self) -> None:
        rd = self.write_reg()
        done_label = self.builder.label("jal_done")
        poison = self.distinct_imm12()
        landing = self.distinct_imm12(exclude=poison)

        self.builder.emit(f"jal  x{rd}, {done_label}")
        self.builder.emit(f"addi x{JUMP_RESULT}, x0, {poison}")
        self.builder.place_label(done_label)
        self.builder.emit(f"addi x{JUMP_RESULT}, x0, {landing}")
        self.builder.emit(f"sw   x{JUMP_RESULT}, {self.builder.next_trace_offset()}(x{ADDR_REG})")

    def branch_operands(self, op: str, taken: bool) -> tuple[int, int]:
        cases = {
            "beq": {True: (7, 7), False: (7, -7)},
            "bne": {True: (7, -7), False: (7, 7)},
            "blt": {True: (-8, 3), False: (9, -2)},
            "bge": {True: (9, -2), False: (-8, 3)},
            "bltu": {True: (3, 9), False: (9, 3)},
            "bgeu": {True: (9, 3), False: (3, 9)},
        }
        return cases[op][taken]

    def write_reg(self) -> int:
        if self.rng.random() < 0.08:
            return 0
        return self.rng.choice(NONZERO_WRITE_REGS)

    def source_reg(self) -> int:
        return self.rng.choice(SOURCE_REGS)

    def imm12(self) -> int:
        if self.rng.random() < self.config.random_imm_rate:
            return self.rng.randint(-2048, 2047)
        return self.rng.choice(INTERESTING_IMM12)

    def distinct_imm12(self, exclude: int | None = None) -> int:
        value = self.imm12()
        while value == exclude:
            value = self.imm12()
        return value


def default_output_path(name: str) -> Path:
    return repo_root_from_script() / "programs" / "asm" / f"{name}.S"


def repo_root_from_script() -> Path:
    return Path(__file__).resolve().parents[1]


def parse_categories(text: str) -> tuple[str, ...]:
    categories = tuple(item.strip() for item in text.split(",") if item.strip())
    return categories


def parse_seed(text: str | None) -> int:
    if text is None:
        return random.SystemRandom().randrange(1 << 32)
    return int(text, 0)


def write_output(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate constrained-random RV32I .S programs for this repo."
    )
    parser.add_argument("--seed", help="integer seed; accepts decimal or 0x-prefixed values")
    parser.add_argument("--instr-count", type=int, default=80, help="number of high-level random ops")
    parser.add_argument(
        "--categories",
        default="alu,mem,branch,u,jump",
        help=f"comma-separated subset of: {','.join(ALL_CATEGORIES)}",
    )
    parser.add_argument("--name", help="assembly label and output basename")
    parser.add_argument("--out", type=Path, help="output .S path; defaults to programs/asm/<name>.S")
    parser.add_argument("--stdout", action="store_true", help="print assembly instead of writing a file")
    parser.add_argument("--signature-words", type=int, default=32, help="number of x-registers to dump")
    parser.add_argument("--scratch-base", type=lambda value: int(value, 0), default=0x100)
    parser.add_argument("--scratch-words", type=int, default=32)
    parser.add_argument(
        "--data-base",
        type=lambda value: int(value, 0),
        default=0,
        help="data window base (default 0 = x0-relative); e.g. 0x80010000 for Spike / FPGA SoC RAM",
    )
    parser.add_argument(
        "--random-imm-rate",
        type=float,
        default=0.25,
        help="probability of choosing a fully random imm12 instead of an edge-biased value",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    seed = parse_seed(args.seed)
    name = args.name or f"random_seed_{seed}"
    config = GeneratorConfig(
        seed=seed,
        name=name,
        instr_count=args.instr_count,
        categories=parse_categories(args.categories),
        output=args.out,
        signature_words=args.signature_words,
        scratch_base=args.scratch_base,
        scratch_words=args.scratch_words,
        random_imm_rate=args.random_imm_rate,
        data_base=args.data_base,
    )

    text = RandomProgramGenerator(config).generate()
    output = config.output or default_output_path(config.name)

    if args.stdout:
        print(text, end="")
    else:
        write_output(output, text)
        print(f"generated {output}")
        print(f"seed {config.seed}")

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except GeneratorError as exc:
        raise SystemExit(f"gen_random_program.py: {exc}")
