name: RTL CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  hex-gen:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y binutils-riscv64-unknown-elf

      - name: Generate hex files
        run: ./scripts/asm_to_hex.sh

      - name: Upload generated hex and dumps
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: generated-asm-hex
          path: |
            programs/hex/*.hex
            sim/build/asm/*.dump
            sim/build/asm/*.pre.S
            sim/build/asm/*.bin
