name: RTL CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  single-cycle:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y make iverilog binutils-riscv64-unknown-elf bsdextrautils

      - name: Check toolchain
        run: |
          riscv64-unknown-elf-as --version
          riscv64-unknown-elf-objcopy --version
          iverilog -V

      - name: Generate hex files
        run: ./scripts/asm_to_hex.sh

      - name: Upload generated hex and dumps
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: generated-asm-hex
          path: |
            programs/hex/*.hex
            sim/build/asm/*.dump
            sim/build/asm/*.pre.S
            sim/build/asm/*.bin

      - name: Run single-cycle simulation
        run: SKIP_ASM=1 ./scripts/run_single_cycle.sh

      - name: Upload simulation logs and waves
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: single-cycle-sim
          path: |
            sim/build/logs/*.log
            sim/build/waves/*.vcd
            sim/build/*.vvp
